import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container } from "postcss";
import CompHeader from './Components/header'
import Footers from "./Components/footer";
import { ShoppingCartProvider } from "../context/ShoppingCartContext";
import ShoppingCart from "./Components/shoppingCart";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shopping",
  description: "Generated by Shoppingj",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-100 text-zinc-900`}>
      <ShoppingCartProvider>
      <CompHeader/>
        {children}
      <Footers/>
      </ShoppingCartProvider>
      </body>
    </html>
  );
}
